image: ruby:2.6.3-buster

before_script:
  - gem install bundler:2.0.2
  - bundle install --jobs $(nproc) --path vendor "${FLAGS[@]}"

.base-test:
  # Cancel if new commits where pushed
  interruptible: true
  # Run only when there is an MR
  only:
    - master
    - merge_requests

  stage: test
  # Use only the following CI runners
  tags:
    - gitlabci-runner-eks-shared-dev

rubocop:
  extends: .base-test
  stage: test
  script:
    - bundle exec rubocop

rspec:
  extends: .base-test
  stage: test
  script:
    - bundle exec rspec

cache:
  key: 'delorean_bundler_cache'
  paths:
    - vendor/ruby

variables:
  GIT_SSL_NO_VERIFY: "true"
  BUNDLER_VERSION: "2.0.2"
  POSTGRES_USER: "runner"
  POSTGRES_PASSWORD: ""
  RAILS_ENV: "test"
  RAILS_DUMP_SCHEMA: "false"

